name:                purp
version:             0.1.0.0
github:              "justinwoo/purp"
license:             BSD3
author:              "Justin Woo"
maintainer:          "@jusrin00"
copyright:           "2018 Justin Woo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/purp#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- text

executables:
  purp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  purp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
